name: Deploy Student ToDo App

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4

      - name: Execute Remote SSH Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_UserName }}
          key: ${{ secrets.SSH_PrivateKey }}
          script: |
            cd /home/huz/studentToDo 
            
            git fetch --all
            git checkout tags/${{ github.ref_name }}
            
            docker compose down || true
            docker compose up -d --build
